force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Max_Pay__c.field-meta.xml
<CustomField>
    <fullName>Max_Pay__c</fullName>
    <label>Max Pay</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Min_Pay__c.field-meta.xml
<CustomField>
    <fullName>Min_Pay__c</fullName>
    <label>Min Pay</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/PositionTriggerHandler.cls
public class PositionTriggerHandler {
    public static void populateData (list<Position__c> posList){
        for(Position__c pos:posList){
            if(pos.Status__c=='New Position'){
                
                if(pos.Min_Pay__c==null){
                pos.Min_Pay__c= 10000;}
                
                if(pos.Open_Date__c==null){
                pos.Open_Date__c= system.Today();}
                
                     
                if(pos.Max_Pay__c == null){
                 pos.Max_Pay__c= 15000;}        
            }             
         }        
    }
    
    public static void taskCreation(list<Position__c> posList){
        list<Task> tasklist = new list<Task>();
        for(Position__c pos:posList){
           if(pos.Status__c=='New Position'){
           
               Task t = new Task();
               t.WhatId = pos.Id;
               t.OwnerId= UserInfo.getUserid();
               t.Status = 'In Progress';
               t.Subject = 'Email';
               t.Priority='High';
               tasklist.add(t);
           }}
        if(!tasklist.isEmpty()){
            insert tasklist;
        }
        
    }

}