force-app/main/default/objects/empdetail__c/empdetail__c.object-meta.xml
<CustomObject>
    <label>empdetail</label>
    <nameField>
        <label>empdetail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>empdetails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/empdetail__c/fields/surname__c.field-meta.xml
<CustomField>
    <fullName>surname__c</fullName>
    <label>surname</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/dmlnew.cls
public class dmlnew 
{ 
    public void method1()
    {
        //empdetail__C e1=new empdetail__c(Name='utkarsh',surname__c='murera',age__c=66,email__c='murera@gmail.com');
        //    insert e1;
      // empdetail__c b1= [SELECT age__c, surname__c, email__c, Name, Id FROM empdetail__c where  surname__c='murera' ];
       // b1.Name='lasan';
       // update b1;
       //empdetail__c b1= [SELECT age__c, surname__c, email__c, Name, Id FROM empdetail__c where  surname__c='murera' ];
        //delete b1;
        //List <empdetail__c> c1 = [ SELECT Id, Name FROM empdetail__c where age__c=66  ALL ROWS ];
        //undelete c1;
       // empdetail__C e1=new empdetail__c(Name='shiva ',surname__c='gautam', age__c=66 ,email__c='shiva@gmail.com');
        //upsert e1 Name;
        

        
        

    }

}