force-app/main/default/objects/calculator__c/calculator__c.object-meta.xml
<CustomObject>
    <label>calculator</label>
    <nameField>
        <label>calculator Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>calculators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/calculator__c/fields/interest__c.field-meta.xml
<CustomField>
    <fullName>interest__c</fullName>
    <label>interest</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/calculator__c/fields/Loan_amount__c.field-meta.xml
<CustomField>
    <fullName>Loan_amount__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/calculator__c/fields/Loan_term__c.field-meta.xml
<CustomField>
    <fullName>Loan_term__c</fullName>
    <label>Loan term</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/trghandlercalculator.cls
public class trghandlercalculator 
    {
        public static void trgcalmethod(list <calculator__c> calc)
        {
            for(calculator__c obj : calc)
            {
                if(obj.Loan_amount__c !=null)
                {
                    obj.interest__c = obj.interest__c + 5;
                    obj.Loan_term__c = obj.Loan_term__c + 5;
                }
                
               
            }
        }
    }