force-app/main/default/objects/Enquiry_Form__c/Enquiry_Form__c.object-meta.xml
<CustomObject>
    <label>Enquiry Form</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Enquiry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enquiry Form</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Enquiry_Form__c/fields/Contact_No__c.field-meta.xml
<CustomField>
    <fullName>Contact_No__c</fullName>
    <label>Contact No.</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Enquiry_Form__c/fields/Date_of_enquiry__c.field-meta.xml
<CustomField>
    <fullName>Date_of_enquiry__c</fullName>
    <label>Date of enquiry</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Enquiry_Form__c/fields/Email_id__c.field-meta.xml
<CustomField>
    <fullName>Email_id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Email id</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Enquiry_Form__c/fields/Parent_name__c.field-meta.xml
<CustomField>
    <fullName>Parent_name__c</fullName>
    <label>Parent name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/firstcontroller.cls
public class firstcontroller {
     
    public string fname{set;get;}
    public string pname{set;get;}
    public string email{set;get;}
 

        public firstcontroller()
    {
        
    }
    public void saverecord()
    {
        Enquiry_Form__c a = new Enquiry_Form__c();
        a.First_Name__c= fname;
        a.Parent_name__c=pname;
        a.Email_id__c=email;
        a.Date_of_enquiry__c=system.today();
        a.Contact_No__c= '9981345888';
        insert a;
}
}